person:
  userName: 'zhangsan \n lisi'
# 单引号会将 \n作为字符串输出  双引号会将 \n作为换行输出
# 双引号不会转义,单引号会转义
  boss: true
  birth: 2021/08/30
  age: 18
#  interests: [篮球,足球]
  interests:
    - 篮球
    - 足球
  animal: [阿猫,阿狗]
#  score:
#    english: 80
#    math: 90
  score: {english: 80,math: 90}
  salarys:
    - 9999
    - 9998
  pet:
    name: 阿狗
    weight: 99.99
  allPets:
    sick:
      - {name: 阿狗,weight: 99.99}
      - name: 阿猫
        weight: 88.88
      - name: 阿虫
        weight: 77.77
    health:
      - {name: 阿花,weight: 199.99}
      - {name: 阿明,weight: 199.99}